namespace DatingApp.API.Models
{
    public class User
    {
        public int  Id { get; set; } //cant validate id, pwhash, pwsalt since they arent generated by user, so we validated dto 
        public string Username { get; set; }
        public byte[] PasswordHash { get; set; }
        public byte[] PasswordSalt { get; set; }
    }
}