using System;
using System.Collections.Generic;

namespace DatingApp.API.Models
{
    public class User
    {
        public int  Id { get; set; } //cant validate id, pwhash, pwsalt since they arent generated by user, so we validated dto 
        public string Username { get; set; }
        public byte[] PasswordHash { get; set; }
        public byte[] PasswordSalt { get; set; }
        public string Gender { get; set;}
        public DateTime DateOfBirth { get; set; }
        public DateTime Created { get; set; }
         public DateTime LastActive { get; set; }
         public string Introduction { get; set; }
         public string LookingFor { get; set; }
         public string Interests { get; set; }
         public string City { get; set; }
         public string Country { get; set; }
         public ICollection<Photo> Photos { get; set; } = new List<Photo>();
         public ICollection<Like> Likers { get; set; }
         public ICollection<Like> Likees { get; set; }
    }
}